# Site settings
title: The Living Well
description: Coming soon.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thelivingwell.co" 
permalink: /:categories/:title

# Build settings
markdown: kramdown


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: post
  -
    scope:
      path: "be"
      type: "posts"
    values:
      category: be
  -
    scope:
      path: "eat"
      type: "posts"
    values:
      category: eat
  -
    scope:
      path: "live"
      type: "posts"
    values:
      category: live
